name: reference_app
description: "Proyecto de referencia para estructurar apps en flutter"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  window_size: ^0.1.0 
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Monocraft
      fonts:
        - asset : assets/fonts/Monocraft.ttf

  assets:
    - assets/images/
    - assets/icons/